### ISSUE TITLE
Erorr.

### ISSUE THREAD

**Issue by 8risingr89** [ZeroDiscord/MusicBot#2]
Logs
Bot is ready to play songs! | Bot created by 0_0
U͎C͎H͎I͎H͎A͎ G͎U͎I͎L͎D͎: Uchiha Daisy#1135 Used play in #🎛music-control
`videoDetails.thumbnail.thumbnails` will be removed in a near future release, use `videoDetails.thumbnails` instead.
Calling `ytdl.getInfo` with a callback will be removed in a near future release. Use async/await.
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:107:11)
    at Url.parse (url.js:155:3)
    at Object.urlParse [as parse] (url.js:150:13)
    at Object.exports.getURLVideoID (/rbd/pnpm-volume/60bd88fa-eda8-433a-be44-29641a79c76b/node_modules/.registry.npmjs.org/ytdl-core/3.1.2/node_modules/ytdl-core/lib/util.js:252:22)
    at Object.exports.getVideoID (/rbd/pnpm-volume/60bd88fa-eda8-433a-be44-29641a79c76b/node_modules/.registry.npmjs.org/ytdl-core/3.1.2/node_modules/ytdl-core/lib/util.js:285:20)
    at Object.exports.<computed> [as getInfo] (/rbd/pnpm-volume/60bd88fa-eda8-433a-be44-29641a79c76b/node_modules/.registry.npmjs.org/ytdl-core/3.1.2/node_modules/ytdl-core/lib/info.js:317:19)
    at Function.exports.<computed> [as getInfo] (/rbd/pnpm-volume/60bd88fa-eda8-433a-be44-29641a79c76b/node_modules/.registry.npmjs.org/ytdl-core/3.1.2/node_modules/ytdl-core/lib/info.js:313:29)
    at /rbd/pnpm-volume/60bd88fa-eda8-433a-be44-29641a79c76b/node_modules/.github.com/ZeroDiscord/ytdl-core-discord/4dc4f176f196403272e468c616bd7ee3578c770a/node_modules/ytdl-core-discord/index.js:24:8
    at new Promise (<anonymous>)
    at download (/rbd/pnpm-volume/60bd88fa-eda8-433a-be44-29641a79c76b/node_modules/.github.com/ZeroDiscord/ytdl-core-discord/4dc4f176f196403272e468c616bd7ee3578c770a/node_modules/ytdl-core-discord/index.js:23:9)
(node:7194) UnhandledPromiseRejectionWarning: Error [VOICE_PLAY_INTERFACE_BAD_TYPE]: Unknown stream type
    at VoiceConnection.play (/rbd/pnpm-volume/60bd88fa-eda8-433a-be44-29641a79c76b/node_modules/.registry.npmjs.org/discord.js/12.5.1/node_modules/discord.js/src/client/voice/util/PlayInterface.js:84:11)
at play (/app/system/music.js:39:8)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:7194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ZeroDiscord** [comment]
This is an unmaintained source. Please refer to my YouTube video for the code
